### ISSUE TITLE
running get and watch on directories

### ISSUE THREAD

**Issue by louis-murray** [mixer/etcd3#38]
Hello!
It seems like the .get and .watch commands only work for a specific key and not the directory although etcd does have this functionality. Am I missing something in the docs or is this a feature that hasn't been implemented yet? I'd be open to implement it if so!

**Comment by connor4312** [comment]
etcd3 doesn't have the concept of directories like etcd2 does. The most 1:1 approach is to use prefixes where you would otherwise use directories. For example:

```ts
etcd3.getAll().prefix('my-directory/subdirectory').then(console.log);
```

Both the [get builder](https://mixer.github.io/etcd3/classes/builder_.multirangebuilder.html#prefix) and [watch builder](https://mixer.github.io/etcd3/classes/watch_.watchbuilder.html#prefix) have prefix methods you can use in this way.

Let me know if you have any other questions!
