### ISSUE TITLE
Why keepalive fire lost after twice ttl

### ISSUE THREAD

**Issue by zyf0330** [mixer/etcd3#57]
```
if (Date.now() - this.lastKeepAlive > 2 * 1000 * this.ttl) {
            this.close();
            this.emit('lost', new errors_1.GRPCConnectFailedError('We lost connection to etcd and our lease has expired.'));
            return;
        }
```
This code is in lease.js `keepalive`, and why `lost` is fired after twice TTL?
Even if thinking about **far past the end of our key's TTL**, I think 3s is ok.

**Comment by connor4312** [comment]
Sorry for the delayed response, on the initial read I read it that lost was fired twice.

It's fired immediately after twice the TTL because that's the time when we consider it 'gone forever'. Without this, we would only notify the caller that the lease is lost if the _server_ tells us it is in response to a heartbeat. But if the server is down entirely, this might not ever end up happening, so eventually we'll bail out and tell the consumer that their lease probably is no longer valid.

**Comment by zyf0330** [comment]
You misunderstood me. The key to my opinion is the word twice. I think that time setting to TTL+3s is enough, twice TTL is too long. Do you think?

**Comment by connor4312** [comment]
Oh. Maybe. TTL should be chosen by consumers based on network latency and load factors. In extreme cases this may naturally be multiple seconds. I think that basing the "give up" trigger based off of the TTL they chose is reasonable. In normal operations that's a code path which is never hit, I'd prefer to be conservative about when we choose to go that way.
