### ISSUE TITLE
grpc version 1.16.1 causes node to be unresponsive inside docker when host is unreachable

### ISSUE THREAD

**Issue by fredantell** [mixer/etcd3#86]
Thank you so much for this library! It seems you are the torch bearer for those of us looking for an easy solution to use etcdv3 from node. You probably don't receive enough thanks for this work.

I spent a couple days this week scratching my head when my node server kept hanging and becoming unresponsive. This code, if run inside a docker node:10 image is enough to reproduce:

```javascript
import { Etcd3 } from "etcd3";

console.log('Start logging...');
setInterval(() => console.log('tick/tock'), 1000);

const etcdClient = new Etcd3({
  hosts: 'localhost:23790' // just make this something unreachable
});

const key = etcdClient.get(`some/key/`); // doesn't really matter b/c host is unreachable anyway

console.log('About to force execution of the call');
const result = key.string();
console.log('Will hang once above call starts processing');
```

Furthermore while this code is sufficient to hang node inside docker, it runs fine on my host machine. When viewing an strace you can see that right before the crash, grpc v1.16.1 will attempt to bind to the ipv6 manifestation of localhost [::1]. Because docker does not have ipv6 turned on by default, the process hangs.
```
[pid    77] connect(20, {sa_family=AF_INET6, sin6_port=htons(2379), inet_pton(AF_INET6, "::1", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=0}, 28 <unfinished ...>
[pid    66] mprotect(0x1a6873984000, 86016, PROT_READ|PROT_EXEC <unfinished ...>
[pid    77] <... connect resumed> )     = -1 EADDRNOTAVAIL (Cannot assign requested address)
[pid    66] <... mprotect resumed> )    = 0
[pid    77] close(20 <unfinished ...>
```

If I update to grpc 1.17-pre1 then the problem goes away and the code executes as expected (the unreachable server rejects the promise and node stays responsive and continues logging out).

I'm not sure if there would be other issues with forcing an update to 1.17-pre1, but I at least wanted to lodge the issue in case some other poor soul faces the same issues I did.

**Comment by connor4312** [comment]
Thanks for opening an issue! This is not really an issue with this library in particular, so I'm going to close it, but I'm sure others will find it useful if they run into the same issue.

I also noticed since a recent Windows update (1810?) that things in Node started binding on ipv6 loopback when referencing localhost, rather than 127.0.0.1. Also on OSX, at least since Sierra. grpc is a native C module that implements its own networking, so it may not have behaved the same way until now, but I've gotten in the habit of always specifying 127.0.0.1 for loopbacks instead of localhost 😛
