### ISSUE TITLE
Deleting multiple keys

### ISSUE THREAD

**Issue by gtamas** [mixer/etcd3#98]
How to remove multiple keys in one request?

I mean, I know this could be done using a range, but I don't understand how to use that.
Let's say I have 3 keys I wanna remove. How do I construct a range for this?

Thanks in advance!

**Comment by connor4312** [comment]
If the keys are sequential in some way (e.g. if they share a common prefix), you can use a range. For instance, `client.delete().prefix('foo');` will delete all keys like "foo1", "foo2", "foo3". Ranges remove all keys in a byte sort order between a start and an end key (if your keys are ascii, this is case-sensitive alphabetic). There's more info on them on the etcd docs.

Etcd otherwise lacks a bulk-arbitrary delete as far as I'm aware, you'll just want to call `client.delete().key('someKey')` three times.

**Comment by gtamas** [comment]
OK I see thank you!
